### ISSUE TITLE
Multiple Events on same location (Map)

### ISSUE THREAD

**Issue by britiger** [jbelien/openstreetmap-calendar-widget#14]
In some cities like Berlin or Zurich there are multiple events per month on same location or like Zurich, there were added all meetups until november. On the map you only get the latest event on this location. If there are more events on the same location you can see the shadow will be more darker.
You should implement a clustering on map or aggregate data for a single location. Or only show the next upcoming event.

**Comment by jbelien** [comment]
Good point ! 👍
