### ISSUE TITLE
Identifying header

### ISSUE THREAD

**Issue by thomersch** [jbelien/openstreetmap-calendar-widget#8]
In case some API changes will be done in the future, it would be handy if we could tell which software is performing the API call. Usually, I would prefer the `User-Agent` header, but this cannot be set from the browser, so I'd suggest `Client-App` with something like `osmcal-widget/x.y.z`.

**Comment by jbelien** [comment]
Did some test with the custom header and apparently, you were right.
You'll need to CORS allow the special header.
It seems to be `Access-Control-Request-Headers` : https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Request-Headers

**Comment by thomersch** [comment]
Alright, we got some headers https://github.com/thomersch/openstreetmap-calendar/commit/5707ced7a668855b844223bf6b8908cd74365910
